mount_project_to_web_server:
  image: busybox:latest
  volumes:
    - .:/var/www/html

db:
  dockerfile: database.dockerfile
  build: .docker
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: allowed
    MYSQL_DATABASE: petrknap_cz
  volume_driver: local
  volumes:
    - petrknap_cz__mysql:/var/lib/mysql
  volumes_from:
    - mount_project_to_web_server:ro

db_test:
  dockerfile: database.dockerfile
  build: .docker
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: allowed
    MYSQL_DATABASE: petrknap_cz

mail:
  image: mailhog/mailhog:latest
  ports:
    - 127.0.0.1:8025:8025

pma:
  image: phpmyadmin/phpmyadmin:latest
  links:
    - db:mysql.petrknap.dev
  environment:
    PMA_HOST: mysql.petrknap.dev
    PMA_USER: root
  ports:
    - 127.0.0.1:8762:80

web:
  dockerfile: web.dockerfile
  build: .docker
  links:
    - db:mysql.petrknap.dev
    - db_test:mysql.petrknap.test
    - mail:smtp.petrknap.dev
  ports:
    - 127.0.0.1:80:80
  volumes_from:
    - mount_project_to_web_server
